{
  description = "Declarative Helix editor themes";

  outputs = { self }: {
    themes = {
      kanabox_default =
        let
          fujiWhite = "#DCD7BA";
          sumiInk0 = "#16161D";
          sumiInk1 = "#1F1F28";
          sumiInk1_5 = "#252530";
          sumiInk2 = "#2A2A37";
          sumiInk3 = "#363646";
          sumiInk4 = "#54546D";
          waveBlue1 = "#252E42";
          waveBlue1_5 = "#2A3D5A";
          waveBlue2 = "#2F496C";
          winterGreen = "#2B3328";
          winterYellow = "#49443C";
          winterRed = "#43242B";
          autumnGreen = "#76946A";
          autumnRed = "#C34043";
          autumnYellow = "#DCA561";
          fujiGray = "#727169";
          oniViolet = "#957FB8";
          crystalBlue = "#7E9CD8";
          springViolet2 = "#9CABCA";
          springBlue = "#7FB4CA";
          lightBlue = "#A3D4D5";
          waveAqua2 = "#7AA89F";
          springGreen = "#98BB6C";
          boatYellow2 = "#C0A36E";
          carpYellow = "#E6C384";
          sakuraPink = "#D27E99";
          waveRed = "#E46876";
          peachRed = "#FF5D62";
          surimiOrange = "#FFA066";
          katanaGray = "#717C7C";
        in {
          "type" = carpYellow;
          "constant" = sakuraPink;
          "constant.numeric" = sakuraPink;
          "constant.character.escape" = surimiOrange;
          "string" = autumnGreen;
          "string.regexp" = springBlue;
          "comment" = katanaGray;
          "variable" = fujiWhite;
          "variable.builtin" = lightBlue;
          "variable.parameter" = fujiWhite;
          "label" = lightBlue;
          "punctuation" = fujiGray;
          "punctuation.delimiter" = fujiGray;
          "punctuation.bracket" = fujiWhite;
          "keyword" = oniViolet;
          "keyword.control" = waveRed;
          "keyword.control.exception" = peachRed;
          "keyword.control.return" = peachRed;
          "keyword.directive" = waveRed;
          "keyword.function" = waveRed;
          "operator" = autumnYellow;
          "function" = springGreen;
          "function.builtin" = springBlue;
          "function.macro" = springBlue;
          "tag" = carpYellow;
          "namespace" = waveAqua2;
          "module" = waveAqua2;
          "attribute" = springBlue;
          "constructor" = carpYellow;
          "special" = surimiOrange;
          
          "markup.heading.marker" = fujiGray;
          "markup.heading.1" = { fg = sakuraPink; modifiers = ["bold"]; };
          "markup.heading.2" = { fg = crystalBlue; modifiers = ["bold"]; };
          "markup.heading.3" = { fg = springGreen; modifiers = ["bold"]; };
          "markup.heading.4" = { fg = carpYellow; modifiers = ["bold"]; };
          "markup.heading.5" = { fg = waveAqua2; modifiers = ["bold"]; };
          "markup.heading.6" = { fg = fujiWhite; modifiers = ["bold"]; };
          "markup.list" = sakuraPink;
          "markup.bold" = { modifiers = ["bold"]; };
          "markup.italic" = { modifiers = ["italic"]; };
          "markup.link.url" = { fg = waveBlue2; modifiers = ["italic"]; };
          "markup.link.label" = waveAqua2;
          "markup.link.text" = waveAqua2;
          "markup.quote" = fujiGray;
          "markup.raw" = carpYellow;
          
          "diff.plus" = { fg = autumnGreen; bg = winterGreen; };
          "diff.delta" = { fg = autumnYellow; bg = winterYellow; };
          "diff.minus" = { fg = autumnRed; bg = winterRed; };
          
          "ui.background" = { bg = sumiInk1; };
          "ui.background.separator" = sumiInk4;
          "ui.cursor" = { fg = sumiInk1; bg = springViolet2; };
          "ui.cursor.match" = { fg = lightBlue; bg = waveBlue1; modifiers = ["bold"]; };
          "ui.cursor.insert" = { fg = sumiInk1; bg = boatYellow2; };
          "ui.cursor.select" = { fg = sumiInk1; bg = sakuraPink; };
          "ui.cursorline.primary" = { bg = sumiInk1_5; };
          "ui.selection" = { bg = sumiInk3; };
          "ui.selection.primary" = { bg = waveBlue1_5; };
          "ui.linenr" = sumiInk4;
          "ui.linenr.selected" = { fg = springViolet2; };
          "ui.statusline" = { fg = springViolet2; bg = sumiInk0; };
          "ui.statusline.inactive" = { fg = sumiInk4; bg = sumiInk0; };
          "ui.statusline.normal" = { fg = sumiInk0; bg = springViolet2; modifiers = ["bold"]; };
          "ui.statusline.insert" = { fg = sumiInk0; bg = autumnYellow; modifiers = ["bold"]; };
          "ui.statusline.select" = { fg = sumiInk0; bg = sakuraPink; modifiers = ["bold"]; };
          "ui.bufferline" = { fg = sumiInk4; bg = sumiInk0; };
          "ui.bufferline.active" = { fg = lightBlue; bg = sumiInk1; modifiers = ["bold"]; };
          "ui.popup" = { fg = sumiInk2; bg = sumiInk2; };
          "ui.window" = { fg = sumiInk4; bg = sumiInk1; };
          "ui.help" = { fg = fujiWhite; bg = sumiInk2; };
          "ui.text" = fujiWhite;
          "ui.text.focus" = lightBlue;
          "ui.menu" = { fg = springViolet2; bg = sumiInk2; };
          "ui.menu.selected" = { fg = sumiInk1; bg = sakuraPink; modifiers = ["bold"]; };
          "ui.virtual.whitespace" = { fg = sumiInk3; };
          "ui.virtual.indent-guide" = { fg = sumiInk3; };
          "ui.virtual.ruler" = { bg = sumiInk3; };
          
          "hint" = springBlue;
          "info" = crystalBlue;
          "warning" = carpYellow;
          "error" = peachRed;
          "diagnostic" = { underline = { style = "line"; }; };
          "diagnositc.hint" = { underline = { color = springBlue; style = "dotted"; }; };
          "diagnositc.info" = { underline = { color = crystalBlue; style = "dotted"; }; };
          "diagnositc.warning" = { underline = { color = carpYellow; style = "curl"; }; };
          "diagnositc.error" = { underline = { color = peachRed; style = "curl"; }; };
        };
      gruvbox_material_dark_medium = 
        let
          bg0 = "#282828";
          bg1 = "#32302f";
          bg2 = "#32302f";
          bg3 = "#45403d";
          bg4 = "#45403d";
          bg_visual_yellow = "#4f422e";
                   
          fg0 = "#d4be98";
          red = "#ea6962";
          orange = "#e78a4e";
          yellow = "#d8a657";
          green = "#a9b665";
          aqua = "#89b482";
          blue = "#7daea3";
          purple = "#d3869b";
          
          grey0 = "#7c6f64";
          grey2 = "#a89984";
        in {     
          "type" = yellow;
          "constant" = purple;
          "constant.numeric" = purple;
          "constant.character.escape" = orange;
          "string" = green;
          "string.regexp" = blue;
          "comment" = grey0;
          "variable" = fg0;
          "variable.builtin" = blue;
          "variable.parameter" = fg0;
          "variable.other.member" = fg0;
          "label" = aqua;
          "punctuation" = grey2;
          "punctuation.delimiter" = grey2;
          "punctuation.bracket" = fg0;
          "keyword" = red;
          "keyword.directive" = aqua;
          "operator" = orange;
          "function" = green;
          "function.builtin" = blue;
          "function.macro" = aqua;
          "tag" = yellow;
          "namespace" = aqua;
          "attribute" = aqua;
          "constructor" = yellow;
          "module" = blue;
          "special" = orange;
          
          "markup.heading.marker" = grey2;
          "markup.heading.1" = { fg = red; modifiers = [ "bold" ]; };
          "markup.heading.2" = { fg = orange; modifiers = [ "bold" ]; };
          "markup.heading.3" = { fg = yellow; modifiers = [ "bold" ]; };
          "markup.heading.4" = { fg = green; modifiers = [ "bold" ]; };
          "markup.heading.5" = { fg = blue; modifiers = [ "bold" ]; };
          "markup.heading.6" = { fg = fg0; modifiers = [ "bold" ]; };
          "markup.list" = red;
          "markup.bold" = { modifiers = [ "bold" ]; };
          "markup.italic" = { modifiers = [ "italic" ]; };
          "markup.link.url" = { fg = blue; modifiers = [ "underlined" ]; };
          "markup.link.text" = purple;
          "markup.quote" = grey2;
          "markup.raw" = green;
          
          "diff.plus" = green;
          "diff.delta" = orange;
          "diff.minus" = red;
          
          "ui.background" = { bg = bg0; };
          "ui.background.separator" = grey0;
          "ui.cursor" = { fg = bg0; bg = fg0; };
          "ui.cursor.match" = { fg = orange; bg = bg_visual_yellow; };
          "ui.cursor.insert" = { fg = bg0; bg = grey2; };
          "ui.cursor.select" = { fg = bg0; bg = blue; };
          "ui.cursorline.primary" = { bg = bg1; };
          "ui.cursorline.secondary" = { bg = bg1; };
          "ui.selection" = { bg = bg3; };
          "ui.linenr" = grey0;
          "ui.linenr.selected" = fg0;
          "ui.statusline" = { fg = fg0; bg = bg3; };
          "ui.statusline.inactive" = { fg = grey0; bg = bg1; };
          "ui.statusline.normal" = { fg = bg0; bg = fg0; modifiers = [ "bold" ]; };
          "ui.statusline.insert" = { fg = bg0; bg = yellow; modifiers = [ "bold" ]; };
          "ui.statusline.select" = { fg = bg0; bg = blue; modifiers = [ "bold" ]; };
          "ui.bufferline" = { fg = grey0; bg = bg1; };
          "ui.bufferline.active" = { fg = fg0; bg = bg3; modifiers = [ "bold" ]; };
          "ui.popup" = { fg = grey2; bg = bg2; };
          "ui.window" = { fg = grey0; bg = bg0; };
          "ui.help" = { fg = fg0; bg = bg2; };
          "ui.text" = fg0;
          "ui.text.focus" = fg0;
          "ui.menu" = { fg = fg0; bg = bg3; };
          "ui.menu.selected" = { fg = bg0; bg = blue; modifiers = [ "bold" ]; };
          "ui.virtual.whitespace" = { fg = bg4; };
          "ui.virtual.indent-guide" = { fg = bg4; };
          "ui.virtual.ruler" = { bg = bg3; };
          
          "hint" = blue;
          "info" = aqua;
          "warning" = yellow;
          "error" = red;
          "diagnostic" = { underline = { style = "curl"; }; };
          "diagnostic.hint" = { underline = { color = blue; style = "dotted"; }; };
          "diagnostic.info" = { underline = { color = aqua; style = "dotted"; }; };
          "diagnostic.warning" = { underline = { color = yellow; style = "curl"; }; };
          "diagnostic.error" = { underline = { color = red; style = "curl"; }; };
        };
    };
  };
}
