{
  "type" = "#78a9ff";
  "constant" = "#be95ff";
  "constant.numeric" = "#82cfff";
  "constant.character.escape" = "#08bdba";
  "string" = "#be95ff";
  "string.regexp" = "#08bdba";
  "comment" = "#525252";
  "variable" = "#dde1e6";
  "variable.builtin" = "#dde1e6";
  "variable.parameter" = "#dde1e6";
  "label" = "#82cfff";
  "punctuation" = "#3ddbd9";
  "punctuation.delimiter" = "#3ddbd9";
  "punctuation.bracket" = "#dde1e6";
  "keyword" = "#78a9ff";
  "keyword.control" = "#78a9ff";
  "keyword.control.exception" = "#82cfff";
  "keyword.control.return" = "#82cfff";
  "keyword.directive" = "#78a9ff";
  "keyword.function" = "#3ddbd9";
  "operator" = "#78a9ff";
  "function" = "#ff7eb6";
  "function.builtin" = "#ff7eb6";
  "function.macro" = "#08bdba";
  "tag" = "#dde1e6";
  "namespace" = "#dde1e6";
  "module" = "#dde1e6";
  "attribute" = "#82cfff";
  "constructor" = "#78a9ff";
  "special" = "#08bdba";

  "markup.heading.marker" = "#3ddbd9";
  "markup.heading.1" = { fg = "#be95ff"; modifiers = [ "bold" ]; };
  "markup.heading.2" = { fg = "#78a9ff"; modifiers = [ "bold" ]; };
  "markup.heading.3" = { fg = "#08bdba"; modifiers = [ "bold" ]; };
  "markup.heading.4" = { fg = "#82cfff"; modifiers = [ "bold" ]; };
  "markup.heading.5" = { fg = "#dde1e6"; modifiers = [ "bold" ]; };
  "markup.heading.6" = { fg = "#ffffff"; modifiers = [ "bold" ]; };
  "markup.list" = "#be95ff";
  "markup.bold" = { modifiers = [ "bold" ]; };
  "markup.italic" = { modifiers = [ "italic" ]; };
  "markup.link.url" = { fg = "#78a9ff"; modifiers = [ "italic" ]; };
  "markup.link.label" = "#dde1e6";
  "markup.link.text" = "#dde1e6";
  "markup.quote" = "#3ddbd9";
  "markup.raw" = "#78a9ff";

  "diff.plus" = { fg = "#42be65"; bg = "#393939"; };
  "diff.delta" = { fg = "#dde1e6"; bg = "#262626"; };
  "diff.minus" = { fg = "#78a9ff"; bg = "#393939"; };

  "ui.background" = { bg = "#161616"; };
  "ui.background.separator" = "#161616";
  "ui.cursor" = { fg = "#161616"; bg = "#dde1e6"; };
  "ui.cursor.match" = { fg = "#82cfff"; bg = "#393939"; modifiers = [ "bold" ]; };
  "ui.cursor.insert" = { fg = "#161616"; bg = "#dde1e6"; };
  "ui.cursor.select" = { fg = "#161616"; bg = "#be95ff"; };
  "ui.cursorline.primary" = { bg = "#262626"; };
  "ui.selection" = { bg = "#393939"; };
  "ui.selection.primary" = { bg = "#393939"; };
  "ui.linenr" = "#525252";
  "ui.linenr.selected" = { fg = "#dde1e6"; };
  "ui.statusline" = { fg = "#ffffff"; bg = "#161616"; };
  "ui.statusline.inactive" = { fg = "#525252"; bg = "#161616"; };
  "ui.statusline.normal" = { fg = "#ffffff"; bg = "#161616"; modifiers = [ "bold" ]; };
  "ui.statusline.insert" = { fg = "#ffffff"; bg = "#ff7eb6"; modifiers = [ "bold" ]; };
  "ui.statusline.select" = { fg = "#ffffff"; bg = "#be95ff"; modifiers = [ "bold" ]; };
  "ui.bufferline" = { fg = "#525252"; bg = "#161616"; };
  "ui.bufferline.active" = { fg = "#82cfff"; bg = "#262626"; modifiers = [ "bold" ]; };
  "ui.popup" = { fg = "#ffffff"; bg = "#262626"; };
  "ui.window" = { fg = "#ffffff"; bg = "#262626"; };
  "ui.help" = { fg = "#ffffff"; bg = "#262626"; };
  "ui.text" = "#ffffff";
  "ui.text.focus" = "#82cfff";
  "ui.menu" = { fg = "#ffffff"; bg = "#262626"; };
  "ui.menu.selected" = { fg = "#ffffff"; bg = "#525252"; modifiers = [ "bold" ]; };
  "ui.virtual.whitespace" = { fg = "#393939"; };
  "ui.virtual.indent-guide" = { fg = "#393939"; };
  "ui.virtual.ruler" = { bg = "#393939"; };

  "hint" = "#ff7eb6";
  "info" = "#78a9ff";
  "warning" = "#82cfff";
  "error" = "#ffffff";
  "diagnostic" = { underline = { style = "line"; }; };
  "diagnostic.hint" = { underline = { color = "#ff7eb6"; style = "dotted"; }; };
  "diagnostic.info" = { underline = { color = "#78a9ff"; style = "dotted"; }; };
  "diagnostic.warning" = { underline = { color = "#82cfff"; style = "curl"; }; };
  "diagnostic.error" = { underline = { color = "#ffffff"; style = "curl"; }; };
}
